### ISSUE TITLE
Overflowing content on smaller screens "Holy Grail" Layout

### ISSUE THREAD

**Issue by oliver41** [codrops/css-reference-issues#38]
I think the section needs a 'flex-basis: auto' in the mq for stretching the section when the screen is getting smaller to prevent the content from overflowing.

@media screen and (max-width:500px) {
    .container {
        flex-direction: column;
        flex-basis: auto;
    }
}

**Comment by SaraSoueidan** [comment]
The aim of this section was to show how the layout is achieved, without getting into making it fully usable/responsive. 

Thank you for the note, though. @botelho could you please add that snippet to the Codrops editor/demo? It's not crucial like I said because it's not part of the objective of the section, but it could be nice to add.

Thanks a lot!

**Comment by botelho** [comment]
Fixed!

**Comment by SaraSoueidan** [comment]
Thank you Pedro :)
