### ISSUE TITLE
:focus on iOS

### ISSUE THREAD

**Issue by jordanmaslyn** [codrops/css-reference-issues#46]
The :focus pseudo-class does not work for at least `a` and `button` elements for iOS Safari (I am on iOS 9). This bug can be recreated by visiting your reference page and clicking the links. They do not receive the outline that you are giving them.

Been working on this issue for a CSS only dropdown component I am trying to build (relying on the :focus state), and found this quirk. Thought it might be worth mentioning in the reference. Haven't been able to test on other touch devices yet.

**EDIT:** Also, thanks for all the work on this and everything else Codrops provides. You guys are an incredible resource!

**Comment by crnacura** [comment]
Thanks a lot for your feedback!

I'm not sure this is a quirk because what exactly does it mean to have "focus" on a mobile device where we only have "touch"? After revisiting the [specs](https://www.w3.org/TR/css3-selectors/#the-user-action-pseudo-classes-hover-act), :focus might simply not be applicable for such a device. 

"The :focus pseudo-class applies while an element has the focus (accepts keyboard or mouse events, or other forms of input).

There may be document language or implementation specific limits on which elements can become :active or acquire :focus."

Thoughts?
