### ISSUE TITLE
border-radius

### ISSUE THREAD

**Issue by seyedi** [codrops/css-reference-issues#51]
Please fix the content and URL of the links in the second paragraph:

 border-top-left-corner ==>  border-top-left-radius and so on...

Thanks

**Comment by dagolinuxoid** [comment]
That's for sure, there isn't such a property as border-top-left-CORNER :)

**Comment by crnacura** [comment]
Of course there isn't :D Thanks for your feedback, we've fixed it now!

**Comment by Jsuriya** [comment]
@crnacura  can u help to fix the issue, am struggling it with for past 10 days and totally unable to understand where. and how change/control the css class.!!

the issue is.. am trying to implement your tymapanas niffty modal effect (slip from top effect) in my inspinia admin theme - in admin panal. i just need the exact effect for my product.

hope you help me 

requirement: 
the even should trigger after clicking on of the menu appear when hover it from side menu bar.
